version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: destructor98/swift-cart:2.0.0
    container_name: swift-cart-users
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_URL:
      REDIS_URL: 
      HOST: localhost
      PORT: 8080
      USER_ACCESS_TOKEN_SECRET: 
      AWS_S3_BUCKET_NAME: 
      AWS_S3_BUCKET_REGION: 
      AWS_S3_BUCKET_ACCESS_KEY_ID: 
      AWS_S3_BUCKET_SECRET_ACCESS_KEY: 
    networks:
      - apoc-smart
  cache:
    container_name: redis
    image: 'redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
    networks:
      - apoc-smart

networks:
  apoc-smart:
    driver: bridge
